---
title: "NBA Shot Charts"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
pagetitle: Austin Daines
---

```{r, echo=FALSE, message=FALSE,warning=FALSE, include=FALSE}
########################################
# LOAD PACKAGES
########################################
library(tidyverse)
library(readr)
library(dplyr)
library(fs)
library(ggplot2)
library(png)
library(grid)
library(jpeg)
library(httr)
library(XML)
library(RCurl)
library(devtools)
#devtools::install_github("lbenz730/ncaahoopR")
#library(ncaahoopR)
#install.packages("cowplot")
library(cowplot)
library(lubridate)
```


```{r, echo=FALSE, message=FALSE,warning=FALSE, include=FALSE}
########################################
# ASSEMBLE SHOT DATA DF
########################################
# Create file path to load all shot data csv's at the same time
file_path <- fs::dir_ls("shot_files_v2")
file_path

# 1.0: for loop method
all_shot_data <- list()

for (i in seq_along(file_path)) {
    all_shot_data[[i]] <- read_csv(
        file = file_path[[i]]
  )
}

# Set column names as names from csv
all_shot_data <- set_names(all_shot_data, file_path)

# 2.0: PURRR MAP method

#file_paths %>% 
 # map(function (path)) {
    #read_csv(path)
 # })

# Create df and bind all shot data 
full_df <- do.call(rbind.data.frame, all_shot_data)
```



```{r, echo=FALSE, message=FALSE,warning=FALSE, include=FALSE}
########################################
# CREATE TEAM COLOR DF
########################################
# Build team and color df
team_name <- unique(full_df$TEAM_NAME, incomparables = FALSE)

# Make column for primary and secondary team colors
primary_color <- c("#CE1141", "#007A33", "#860038", "#002A60", "#00471B", "#006BB6", "#002B5C",
                   "#0077C0", "#98002E", "#E03A3E", "#006BB6", "#CE1141", "#002D62", "#C8102E",
                   "#000000", "#0C2340", "#CE1141", "#5A2D81", "#00538C", "#0E2240", "#002B5C", "#00653A",
                   "#552583", "#1D1160", "#1D428A", "#C8102E", "#00B2A9", "#E03A3E", "#1D1160", "#002B5C",
                   "#5D76A9", "#008080", "#FF6F00", "#008080", "#007AC1", "#000000", "#0C2340", "#C8102E")
secondary_color <- c("#000000", "#BA9653", "#FDBB30", "#CD1041", "#EEE1C6", "#ED174C", "#E31837",
                     "#C4CED4", "#F9A01B", "#FFCD00", "#F58426", "#000000", "#FDBB30", "#1D42BA",
                     "#C4CED4", "#236192", "#FFFFFF", "#63727A", "#002B5E", "#FEC524", "#00471B", "#FFC200",
                     "#FDB927", "#E56020", "#FFC72C", "#1D428A", "#FFFFFF", "#000000", "#00788C", "#E31837",
                     "#5D76A9", "#FDBB30", "#010048", "#FDBB30", "#EF3B24", "#FFFFFF", "#C8102E", "#1D428A")
third_color <- c("#FFFFFF", "#FFFFFF", "#000000", "#777D84", "#0077C0", "#002B5C", "#C4CED4", 
                 "#000000", "#000000", "#000000", "#FFFFFF", "#A1A1A4", "#BEC0C2", "#BEC0C2",
                 "#FFFFFF", "#9EA2A2", "#000000", "#000000", "#B8C4CA", "#1D428A", "#F9A01B", "#FFFFFF",
                 "#000000", "#000000", "#FFFFFF", "#BEC0C2", "#040204", "#FFFFFF", "#A1A1A4", "#C4CED4",
                 "#F5B112", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#002D62", "NA", "#85714D", "#BEC0C2")
fourth_color <- c("NA", "#000000", "#041E42", "#FFFFFF", "#000000", "#FFFFFF", "#FFFFFF", 
                  "#FFFFFF", "#FFFFFF", "#FFFFFF", "#000000", "#B4975A", "#FFFFFF", "#FFFFFF",
                  "NA", "#78BE20", "#C4CED4", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "NA",
                  "#FFFFFF", "#FFFFFF", "NA", "#000000", "#E43C40", "NA", "#FFFFFF", "#FFFFFF",
                  "#707271", "NA", "NA", "NA", "#FFFFFF", "NA", "#FFFFFF", "#FFFFFF")

# Join columns for team colors 
team_colors <- data.frame(team_name, primary_color, secondary_color, third_color, fourth_color)

# Insert any player name (from 1996-today) where prompted in the console
#player_name <- readline(prompt="Enter player name: ")
player_name <- "Dirk Nowitzki"

# Find player ID based on player name
player_id <- full_df$PLAYER_ID[match(player_name, full_df$PLAYER_NAME)]

# Use player ID to extract all made shots with that ID
shots <- full_df[full_df$PLAYER_ID==player_id,]

# List unique teams played for
teams_played_for <- unique(shots$TEAM_NAME, incomparables = FALSE)

# Print list of unique teams
print(teams_played_for)

# Filter for specific team or season if needed
#season_shots <- shots[shots$GAME_DATE...]
#team_shots <- shots[shots$TEAM_NAME==""]

# Change Game Date column to Date type
shots$GAME_DATE <- ymd(shots$GAME_DATE)
years_played <- year(shots$GAME_DATE)
rookie_year <- as.character(min(years_played))
final_year <- as.character(max(years_played))

# Enter one of the team names in the console where prompted
#team_color_scheme <- readline(prompt="Enter team name from list above: ")
team_color_scheme <- "Dallas Mavericks"

# Get color one
color1 <- team_colors$primary_color[match(team_color_scheme, team_colors$team_name)]
# Get color two
color2 <- team_colors$secondary_color[match(team_color_scheme, team_colors$team_name)]
# Get color three
color3 <- team_colors$third_color[match(team_color_scheme, team_colors$team_name)]
# Get color four
color4 <- team_colors$fourth_color[match(team_color_scheme, team_colors$team_name)]
# Flip X-coordinates in order to use accurate data in plot
shots$LOC_X <- shots$LOC_X * (-1)
```


### Taking NBA Shot chart data that looks like this...

```{r, echo=FALSE, message=FALSE, warning=FALSE, dpi = 200}
########################################
# PLOT ROUGH DRAFT
########################################
# Plot rough copy on normal grid
ggplot(shots, aes(x=LOC_X, y=LOC_Y)) + 
  geom_point(alpha= 0.50, color = "black") +
  theme_minimal()
```

___

```{r, echo=FALSE, message=FALSE,warning=FALSE, include=FALSE}
########################################
# DRAWING THE COURT
########################################
# Creating court function and plotting
circle_points = function(center = c(0, 0), radius = 1, npoints = 360) {
  angles = seq(0, 2 * pi, length.out = npoints)
  return(data_frame(x = center[1] + radius * cos(angles),
                    y = center[2] + radius * sin(angles)))
}

# Court Dimensions & lines
width = 500
baseline_coord = -52.5
height = (940 / 2) + baseline_coord
key_height = 190 + baseline_coord
inner_key_width = 120
outer_key_width = 160
backboard_width = 60
backboard_offset = -12.5
neck_length = 5.0
hoop_radius = 7.5
hoop_center_y = backboard_offset + neck_length + hoop_radius
three_point_radius = 237.3
three_point_side_radius = 220
three_point_side_height = 140 + baseline_coord
hash_width = 30
hash_height = 280 + baseline_coord
free_throw_hash = 10
fth_height = baseline_coord + 70
base_hash_height = 7.5
jersey_start = height - (inner_key_width / 4)
jersey_width = inner_key_width - 15
jersey_height = jersey_start + (key_height * 0.7)
shoulder_width = 12.5
jersey_side = key_height * 0.5

# Court themes
court_themes = list(
  light = list(
    court = 'floralwhite',
    lines = '#999999',
    text = '#222222',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 1,
    hex_border_color = "#000000"
  ),
  dark = list(
    court = '#000004',
    lines = '#999999',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "#000000"
  ),
  ppt = list(
    court = color2,
    lines = 'white',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = color2
  )
)

# Function to create court based on given dimensions
plot_court = function(court_theme = court_themes$light, use_short_three = FALSE) {
  if (use_short_three) {
    three_point_radius = 22
    three_point_side_height = 0
  }
  
  court_points = data_frame(
    x = c(width / 2, width / 2, -width / 2, -width / 2),
    y = c(height, baseline_coord, baseline_coord, height),
    desc = "perimeter"
  )
  
  court_points = bind_rows(court_points , data_frame(
    x = c(-width / 2, (-width / 2) + (1.5875 * inner_key_width)),
    y = c(height, height),
    desc = "left_half"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c((width / 2) - (1.5875 * inner_key_width), width / 2),
    y = c(height, height), 
    desc = "right_half"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(outer_key_width / 2, outer_key_width / 2, -outer_key_width / 2, -outer_key_width / 2),
    y = c(baseline_coord, key_height, key_height, baseline_coord),
    desc = "outer_key"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(inner_key_width / 2, inner_key_width / 2, -inner_key_width / 2, -inner_key_width / 2),
    y = c(baseline_coord, key_height, key_height, baseline_coord),
    desc = "inner_key"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c((-outer_key_width / 2) - free_throw_hash, -outer_key_width / 2),
    y = c(fth_height, fth_height),
    desc = "ft_hash1"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(-backboard_width / 2, backboard_width / 2),
    y = c(backboard_offset, backboard_offset),
    desc = "backboard"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(-backboard_width / 2, backboard_width / 2),
    y = c(backboard_offset - 0.5, backboard_offset - 0.5),
    desc = "backboard_two"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(-backboard_width / 2, backboard_width / 2),
    y = c(backboard_offset + 1.0, backboard_offset + 1.0),
    desc = "backboard_three"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(-backboard_width / 2, backboard_width / 2),
    y = c(backboard_offset + 1.5, backboard_offset + 1.5),
    desc = "backboard_four"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(-width / 2, (-width / 2) + hash_width),
    y = c(hash_height, hash_height),
    desc = "left_hash"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c((width / 2) - hash_width, width / 2),
    y = c(hash_height, hash_height), 
    desc = "right_hash"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c((-outer_key_width / 2) - free_throw_hash, -outer_key_width / 2),
    y = c(fth_height, fth_height),
    desc = "ft_hash1"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c((-outer_key_width / 2) - free_throw_hash, -outer_key_width / 2),
    y = c(fth_height + 10, fth_height + 10),
    desc = "ft_hash2"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c((-outer_key_width / 2) - free_throw_hash, -outer_key_width / 2),
    y = c(fth_height + 40, fth_height + 40),
    desc = "ft_hash3"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c((-outer_key_width / 2) - free_throw_hash, -outer_key_width / 2),
    y = c(fth_height + 70, fth_height + 70),
    desc = "ft_hash4"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c((outer_key_width / 2) + free_throw_hash, outer_key_width / 2),
    y = c(fth_height, fth_height),
    desc = "ft_hash1a"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c((outer_key_width / 2) + free_throw_hash, outer_key_width / 2),
    y = c(fth_height + 10, fth_height + 10),
    desc = "ft_hash2a"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c((outer_key_width / 2) + free_throw_hash, outer_key_width / 2),
    y = c(fth_height + 40, fth_height + 40),
    desc = "ft_hash3a"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c((outer_key_width / 2) + free_throw_hash, outer_key_width / 2),
    y = c(fth_height + 70, fth_height + 70),
    desc = "ft_hash4a"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c((-outer_key_width / 2) - 30, (-outer_key_width / 2) - 30),
    y = c(base_hash_height + baseline_coord, baseline_coord),
    desc = "base_hash_l"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c((outer_key_width / 2) + 30, (outer_key_width / 2) + 30),
    y = c(base_hash_height + baseline_coord, baseline_coord),
    desc = "base_hash_r"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(0, -0), 
    y = c(backboard_offset, backboard_offset + neck_length), 
    desc = "neck"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(0.5, 0.5), 
    y = c(backboard_offset, backboard_offset + neck_length), 
    desc = "necka"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(1.5, 1.5), 
    y = c(backboard_offset, backboard_offset + neck_length), 
    desc = "neckaa"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(-0.5, -0.5), 
    y = c(backboard_offset, backboard_offset + neck_length), 
    desc = "neckb"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(-1.5, -1.5), 
    y = c(backboard_offset, backboard_offset + neck_length), 
    desc = "neckb"
  ))
  
  foul_circle = circle_points(center = c(0, key_height - 1), radius = inner_key_width / 2)
  
  foul_circle_top = filter(foul_circle, y > key_height - 1) %>%
    mutate(desc = "foul_circle_top")
  
  foul_circle_bottom = filter(foul_circle, y < key_height) %>%
    mutate(
      angle = atan((y - key_height) / x) * 180 / pi,
      angle_group = floor((angle - 5.625) / 11.25),
      desc = paste0("foul_circle_bottom_", angle_group)
    ) %>%
    filter(angle_group %% 2 == 0) %>%
    select(x, y, desc)
  
  hoop = circle_points(center = c(0, hoop_center_y), radius = hoop_radius) %>%
    mutate(desc = "hoop")
  
  restricted = circle_points(center = c(0, hoop_center_y), radius = 40) %>%
    filter(y >= hoop_center_y) %>%
    mutate(desc = "restricted")
  
  three_point_circle = circle_points(center = c(0, hoop_center_y), radius = three_point_radius) %>%
    filter(y >= three_point_side_height, y >= hoop_center_y)
  
  three_point_line = data_frame(
    x = c(three_point_side_radius, three_point_side_radius, three_point_circle$x, -three_point_side_radius,  -three_point_side_radius),
    y = c(baseline_coord, three_point_side_height, three_point_circle$y, three_point_side_height, baseline_coord),
    desc = "three_point_line"
  )
  
  court_points = bind_rows(
    court_points,
    #half_circle_bottom,
    #jersey_neck_bottom,
    foul_circle_top,
    foul_circle_bottom,
    hoop,
    restricted,
    three_point_line
  )
  
  court_points <- court_points
  
  # Final plot creation
  ggplot() +
    geom_point(data = shots, aes(x=LOC_X, y=LOC_Y), size =0.5, color = color3) +
    geom_path(
      data = court_points,
      aes(x = x, y = y, group = desc),
      color = court_theme$lines) +
    coord_fixed(ylim = c(baseline_coord, 470), xlim = c(-250, 250)) +
    theme_minimal(base_size = 22) +
    theme(text = element_text(color = court_theme$text),
      ### color scheme for background
      plot.background = element_rect(fill = color2, color = color2),
      panel.background = element_rect(fill = court_theme$court, color = court_theme$court),
      panel.grid = element_blank(),
      panel.border = element_blank(),
      axis.text = element_blank(),
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      legend.background = element_rect(fill = court_theme$court, color = court_theme$court)
    )
}
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
########################################
# SET VARIABLES FOR JERSEY AND TITLE
########################################
jersey_color <- color3
number_color <- color3
# change total fg from x,xxx to x.xK
fg_made <- as.numeric(nrow(shots))
fg_made_k <- sprintf("%sK", format(round(fg_made/1000, 1), dec="."))
## change total 3fg from x,xxx to x.xK
fg_threepoint <- as.numeric(nrow(shots[shots$SHOT_TYPE=="3PT Field Goal",]))
fg_made_three_k <- sprintf("%sK", format(round(fg_threepoint/1000, 1), dec="."))

```



### And turning it into this 

```{r, echo=FALSE, message=FALSE, warning=FALSE, include= FALSE, dpi = 200}
########################################
# PLOT SHOTS ON COURT
########################################
final <- plot_court(court_themes$ppt, use_short_three = F) +
  scale_x_continuous(limits = c(-250, 250)) +
  scale_y_continuous(limits = c(baseline_coord, 500))

#ggdraw(final) + theme(plot.background = element_rect(fill= color1, color = NA))

#ggsave(paste0(player_name, ".png"), height = 10, width = 8, dpi = 300)

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
########################################
# JERSEY
########################################
jf <- data.frame(
  #jersey bottom
  x1= jersey_width/3.5, x2= -jersey_width/3.5, 
  y1= jersey_start, y2= jersey_start, 
  # jersey left side
  x3= -jersey_width/3.5 + 1.0, x4= -jersey_width/3.5 + 1.0,
  y3= jersey_start - 1.0, y4= jersey_start + jersey_side,
  # jersey right side
  x5= jersey_width/3.5 - 1.0, x6= jersey_width/3.5 - 1.0,
  y5= jersey_start - 1.0, y6= jersey_start + jersey_side,
  # jersey left top
  x7= (-jersey_width / 10) - shoulder_width, x8= -jersey_width / 10,
  y7= jersey_height, y8= jersey_height,
  # jersey right top
  x9= (jersey_width / 10) + shoulder_width, x10= jersey_width / 10,
  y9= jersey_height, y10= jersey_height,
  # jersey neck
  x11= -jersey_width / 10 - 2.0, x12= jersey_width / 10 + 2.0,
  y11= jersey_height + 0.75, y12= jersey_height + 0.75)
# jersey sleeve
left_curve <-curveGrob(0, 0, 1, 1, default.units = "npc",
                       curvature = 0.3, angle = 50, ncp = 50, shape = 1,
                       square = FALSE, squareShape = 1,
                       inflect = FALSE, open = TRUE,
                       debug = FALSE,
                       name = NULL, gp = gpar(col=jersey_color, lwd=3.5), vp = NULL)
# jersey sleeve
right_curve <-curveGrob(0, 1, 1, 0, default.units = "npc",
                        curvature = 0.3, angle = 130, ncp = 50, shape = 1,
                        square = FALSE, squareShape = 1,
                        inflect = FALSE, open = TRUE,
                        debug = FALSE,
                        name = NULL, gp = gpar(col=jersey_color, lwd=3.5), vp = NULL)
# add segments to outline jersey
final <- final + 
  geom_segment(aes(x=x1, y=y1, xend=x2, yend=y2), color= jersey_color, size = 1.5, data=jf)

final <- final +
  geom_segment(aes(x=x3, y=y3, xend=x4, yend=y4), color= jersey_color, size = 1.5, data=jf)

final <- final +
  geom_segment(aes(x=x5, y=y5, xend=x6, yend=y6), color= jersey_color, size = 1.5, data=jf)

final <- final +
  geom_segment(aes(x=x7, y=y7, xend=x8, yend=y8), color= jersey_color, size = 1.5, data=jf)

final <- final +
  geom_segment(aes(x=x9, y=y9, xend=x10, yend=y10), color= jersey_color, size = 1.5, data=jf) +
  geom_curve(aes(x=x11, y=y11, xend=x12, yend=y12), color= jersey_color, size = 1.5, data=jf, curvature = 1) +
  annotation_custom(grob = left_curve, -jersey_width/3.5 + 1.0, -jersey_width/10 - shoulder_width + 1.0, 
                    jersey_height,(jersey_start - 1.0) + jersey_side) +
  annotation_custom(grob = right_curve, jersey_width/3.5 - 1.0, jersey_width/10 + shoulder_width - 1.0,
                    jersey_height, (jersey_start - 1.0) + jersey_side) +
  # total FG made
  annotate("text", label=paste0(fg_made_k, " FG"), 
          x=-180, y=480, color = color3, size = 6, fontface = "bold") +
  # total 3pt made
  annotate("text", label=paste0(fg_made_three_k, " 3PT"), 
           x=180, y=480, color = color3, size = 6, fontface = "bold") +
  # team played for
  annotate("text", label=paste0(team_color_scheme), 
           x=-180, y=440, color = color3, size = 4, fontface = "italic") +
  # years of chart
  annotate("text", label=paste(rookie_year, final_year, sep = " - "), 
         x=180, y=440, color = color3, size = 4, fontface = "italic") +
  # jersey number
  annotate("text", label="41", 
           x=0, y=435, color = number_color, size = 8, fontface = "bold")
```


```{r, echo=FALSE, message=FALSE, warning=FALSE, include = TRUE, dpi = 200}
########################################
# DRAW FINAL PRODUCT
########################################
ggdraw(final) + theme(plot.background = element_rect(fill= color2, color = NA))

```

